version: '3.8'
services:
  server:
    build: ./server
    container_name: java_server
    restart: always
  agent:
    build: ./agent
    container_name: java_agent
    restart: always
    ports:
      - '8080:8080'